name: Test & Build
on: [push]

jobs:
  test-and-build:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: Test
        working-directory: internal
        run: |
          go test ./...
      - name: Build tool
        working-directory: cmd/winsible
        run: |
          go build
